SIM ?= icarus
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES += $(PWD)/../src/project.v
VERILOG_SOURCES += $(PWD)/tb.v
TOPLEVEL = tt_um_jonathan_logic_lock 
MODULE = test
include $(shell cocotb-config --makefiles)/Makefile.sim
